Zrobiona baza danych bez usuwania
Lokinado/flutter_inventory_app pull request #17
Opened 2023-05-26 13:23 UTC by Sokulele

Zrobiona baza danych - dodawanie i modyfikowanie pięter, pokoi, rodzai przedmiotów jak i samych przedmiotów. 
Pisalem to oddzielnie od tego co jest na mainie, trzeba zrobić integracje z głównym mainem.
Sam wygląd jest testowy, dla wygody, zeby zobaczyć czy wszystko działa.

2023-05-28 12:04 UTC, Lokinado commented
Notka dla odwiedzających ten PR:
Będzie trzeba przy merge'owaniu jakoś połączyć to z obecną wersją z main'a. Ten kod powstawał oddzielnie od głównego repo już od bardzo dawna więc UI i wszystko jest zrobione kompletnie inaczej. Niezbędne będzie posprzątanie w plikach (np. jest material.dart i materials.dart). No i musi jakaś dobra dusza dopisać jakiś kawałek kodu który ogarnia usuwanie z bazy danych.

2023-05-28 13:07 UTC, Sokulele commented
Znalazlem buga, który nie dodaje barcode do bazy danych, wydaje mi się, że znalazłem rozwiązanie. Dodam rozwiązanie dzisiaj wieczorem.

2023-05-28 19:19 UTC, Sokulele commented
Dodalem commita 'aaa' bo cos bylo nietak z nazwa, w/e. Naprawilem błąd o którym wspomniałem, teraz dodawanie przedmiotów śmiga. Również zabezpieczyłem edytowanie nazw wszystkich obiektów przed pustymi stringami. Miłego wieczoru

2023-05-29 18:32 UTC, weomweom commented
W dodawaniu piętra dało się wprowadzić emotki, same spacje, różne znaki i myślę że można by było ograniczyć wporowadzenie nazwy tylko do liter i cyfr (o ile jest taka potrzeba)

Moim zdaniem też fajnie by było ograniczyć długość nazwy bo dało się wprowadzić baaaaardzoooo długie stringi, no i z tym wiąże się robienie userfreindly komunikatów o maksymalnej długości

Do tego nie dało się odpalić listę piętr :c
![image](https://github.com/Lokinado/flutter_inventory_app/assets/95056603/a640e794-6952-4895-a69f-af5612c18632)

2023-05-29 18:40 UTC, weomweom requested changes
napisalam w komentarzu, ale na wszelki przypadek zostawiam duplikat
![image](https://github.com/Lokinado/flutter_inventory_app/assets/95056603/0bdfeb74-dac4-41fd-9183-885214352c60)

2023-05-29 19:34 UTC, Lokinado approved these changes
No trochę jeszcze nie jest zrobione ale wrzućmy to na maina

2023-05-29 19:37 UTC, Sokulele commented
> ![image](https://user-images.githubusercontent.com/95056603/241790373-0bdfeb74-dac4-41fd-9183-885214352c60.png)

Wszystko powinno działać, przynajmniej innym działa. Odnosząc się do uwagi na temat długości i dodawania przedziwnych znaków, zostanie to naprawione kiedy będzie zintegrowane gui Dawida z moją bazą. Tak samo wtedy dodam usuwanie z db, nie ma co utrudniać w tym momencie innym.

2023-06-02 07:35 UTC, Sokulele commented
Przeniosłem projekt na baze produkcyjną, gdzie jest zaimplementowana autoryzacja. Teraz baza przedmiotow i logowanie jest na tej samej bazie, więc nie powinno być problemów.

2023-06-05 19:32 UTC, closed without merging