login screen z poprawieniem niezgodnosci w plikach
Lokinado/flutter_inventory_app pull request #9
Opened 2023-04-05 07:09 UTC by ArekAff

Poprawiłem swój wczorajszy błąd związany ze zrobieniem nowego projektu i po prostu wrzucenia go na brancha oraz dodałem foler "web" aby można było na szybko kompilować sobie kod w przeglądarce żeby nie zawsze trzeba było odpalać emulatora androida

2023-04-05 17:26 UTC, Lokinado reviewed
Sprawdziłem sobie zawartość folderu web i zhostowałem sobie lokalnie te pliki strony i nie wiem czy coś źle robie ale nie działa ten webowy podgląd. Konsola inspektora w chromie jęczy że "Failed to load resource: the server responded with a status of 404 (Not Found)" dla pliku flutter.js którego najwyraźniej nie ma

2023-04-05 19:45 UTC, ArekAff commented
Sprawdziłem u siebie używając vs code i android studio, w obu przypadkach u mnie działa więc nie mam pojęcia jak mogę naprawić ten problem

2023-04-17 14:32 UTC, MaciekSIeradz requested changes
Ekran napisany w sposób nieprawidłowy. Nie przechodzi testu, polegającego na wczytaniu głównego Widgetu. Komunikat:
The following assertion was thrown during layout:
A RenderFlex overflowed by 4.0 pixels on the bottom.

2023-05-09 20:27 UTC, ArekAff commented
Dodałem login i stone główna login to test@gmail.com haslo to test123 jak wejdzie sie na strone głowną to na razie nr budynku sali itp sa zhardcodowane bo pewnie powinno sie wziac to z jakiejs metody ale to juz nie moja praca no i zrobilem bottom appbar od razu

2023-05-26 12:08 UTC, closed without merging